"""Markdown renderings of the B1 result tables (so the report quotes the CSVs, never hand-copied numbers).

    python -m qlo.b1.report_tables            # writes results/b1_entangling/tables.md
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[3]
RES = ROOT / "results" / "b1_entangling"
FAM = {"rx_product": "RX product", "hea_ring": "HEA", "rxry_czbrick": "RXRY-CZ"}


def _ci(r, m: str, d: int = 3) -> str:
    return f"{r[m]:+.{d}f} [{r[f'{m}_ci_lo']:+.{d}f}, {r[f'{m}_ci_hi']:+.{d}f}]"


def main_table_md(main: pd.DataFrame, fit_range: str) -> str:
    m = main[main.fit_range == fit_range]
    head = ("| family | depth | position | n range | b_S | b_r | b_LE | b_SWAP | gap obs (b_SWAP - b_LE) | gap pred (b_S) | eps_gap | "
            "ratio obs | ratio pred | concentration | outcome |\n|" + "---|" * 15 + "\n")
    rows = []
    for _, r in m.iterrows():
        depth = {"product": "-", "d2": "2", "d4": "4", "dn": "n"}[r.regime]
        rows.append(f"| {FAM[r.family]} | {depth} | {r.position} | {r.n_fit_range} | {_ci(r, 'b_S')} | {_ci(r, 'b_r')} | {_ci(r, 'b_LE')} | "
                    f"{_ci(r, 'b_SWAP')} | {_ci(r, 'gap_obs')} | {r.gap_pred:+.3f} | {_ci(r, 'eps_gap')} | {_ci(r, 'ratio_obs', 2)} | "
                    f"{_ci(r, 'ratio_pred', 2)} | {r.concentration} | {r.rule_check} / {r.case} |")
    return head + "\n".join(rows) + "\n"


def residual_table_md(main: pd.DataFrame, fit_range: str) -> str:
    m = main[main.fit_range == fit_range]
    head = ("| family | depth | position | eps_LE [boot CI] | eps_LE pct | eps_SWAP [boot CI] | eps_SWAP pct | eps_gap [boot CI] | eps_gap pct | "
            "eps_gap / b_S | within +-0.02 |\n|" + "---|" * 11 + "\n")
    rows = []
    for _, r in m.iterrows():
        depth = {"product": "-", "d2": "2", "d4": "4", "dn": "n"}[r.regime]
        rows.append(f"| {FAM[r.family]} | {depth} | {r.position} | {_ci(r, 'eps_LE', 4)} | [{r.eps_LE_pct_lo:+.4f}, {r.eps_LE_pct_hi:+.4f}] | "
                    f"{_ci(r, 'eps_SWAP', 4)} | [{r.eps_SWAP_pct_lo:+.4f}, {r.eps_SWAP_pct_hi:+.4f}] | {_ci(r, 'eps_gap', 4)} | "
                    f"[{r.eps_gap_pct_lo:+.4f}, {r.eps_gap_pct_hi:+.4f}] | {r.eps_gap / r.b_S:+.3f} | "
                    f"{'yes' if r.eps_gap_equivalent_within_margin else 'no'} |")
    return head + "\n".join(rows) + "\n"


def concentration_md(main: pd.DataFrame, fit_range: str) -> str:
    m = main[main.fit_range == fit_range]
    head = ("| family | depth | position | median S at first n | median S at last n | mean R^2 (log S) | b_S lower / upper half | "
            "curvature rel | class |\n|" + "---|" * 9 + "\n")
    rows = []
    for _, r in m.iterrows():
        depth = {"product": "-", "d2": "2", "d4": "4", "dn": "n"}[r.regime]
        rows.append(f"| {FAM[r.family]} | {depth} | {r.position} | {r.median_S_first_n:.3g} | {r.median_S_last_n:.3g} | {r.mean_r2_S:.4f} | "
                    f"{r.b_S_lower_half:.3f} / {r.b_S_upper_half:.3f} | {r.curvature_rel:.3f} | {r.concentration} |")
    return head + "\n".join(rows) + "\n"


def doubling_md(main: pd.DataFrame, fit_range: str) -> str:
    m = main[main.fit_range == fit_range]
    head = ("| family | depth | position | b_r / b_S | b_r CI has 0 | eligible | ratio obs [CI] | ratio pred [CI] | obs - pred [CI] | "
            "consistent with 2 |\n|" + "---|" * 10 + "\n")
    rows = []
    for _, r in m.iterrows():
        depth = {"product": "-", "d2": "2", "d4": "4", "dn": "n"}[r.regime]
        c2 = "-" if pd.isna(r.ratio_consistent_with_2) else ("yes" if r.ratio_consistent_with_2 in (True, "True") else "no")
        rows.append(f"| {FAM[r.family]} | {depth} | {r.position} | {r.br_over_bS:+.3f} | {'yes' if r.br_ci_contains_0 else 'no'} | "
                    f"{'yes' if r.doubling_test_eligible else 'no'} | {_ci(r, 'ratio_obs', 3)} | {_ci(r, 'ratio_pred', 3)} | "
                    f"{_ci(r, 'ratio_diff', 3)} | {c2} |")
    return head + "\n".join(rows) + "\n"


def write_all(res: Path = RES) -> Path:
    main = pd.read_csv(res / "main_table.csv")
    parts = []
    for fr in ("primary", "secondary_n_ge_8"):
        parts += [f"## Main table ({fr})\n", main_table_md(main, fr), f"\n## Prediction residuals ({fr})\n", residual_table_md(main, fr),
                  f"\n## Concentration diagnostics ({fr})\n", concentration_md(main, fr), f"\n## Exponent-doubling check ({fr})\n",
                  doubling_md(main, fr), "\n"]
    path = res / "tables.md"
    path.write_text("# B1 tables (generated by qlo.b1.report_tables from main_table.csv)\n\n" + "\n".join(parts))
    return path


if __name__ == "__main__":
    print(write_all())
